name: Deploy to server
# This workflow deploys the application to a server using SSH.
on: 
  push:
    branches:
      - main
      - second
jobs:
  first_job:
    name : "First Job" # This job runs first
    runs-on: ubuntu-latest
    outputs:
      my_variable: ${{ steps.step_1.outputs.my_variable }} # This output can be used in other jobs
    env:
      NAME : "World"
    steps:
      - name: Hola mundo # This job runs first
        run: echo "Hola ${{ env.NAME }}"
      - name: Working Directory
        run: ls -la # This job lists the files in the current directory
      - name: action
        uses: actions/checkout@v4 # This job checks out the code from the repository
      - name: Working Directory after Action
        run: ls -la # This job lists the files in the current directory
      - name: Working Directory after Action 2
        id: step_1
        run: echo "my_variable=Hola Mundo" >> $GITHUB_OUTPUT
      - name: Obtener mensaje
        run: echo "${{ steps.step_1.outputs.my_variable }}" # This job retrieves the variable set in the previous step
  second_job:
    if : ${{ github.ref == 'refs/heads/main' }} # This job runs only on the main branch
    # It depends on the first_job to complete before it runs
    needs: first_job # This job depends on the first_job
    runs-on: ubuntu-latest

    env :
      SALIDA : ${{ needs.first_job.outputs.my_variable }} # This job uses the output from the first_job

    steps:
      - name: Hola mundo
        run: echo "Hola mundo segundo ${{ github.ref }} "
      - name: Get Message
        run: echo "This is a message ${{ env.SALIDA }} "
      - name: Generar Archivo
        run: echo "Test File, hello" >> test.log # This job generates a file
      - name: Upload Artifact
        uses: actions/upload-artifact@v4 # This job uploads the file as an artifact
        with:
          name: test-artifact
          path : test.log # This job uploads the file as an artifact
  third_job:
    runs-on: ubuntu-latest
    needs: second_job # This job depends on the second_job to complete before it runs
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4 # This job downloads the artifact uploaded by the second_job
        with:
          name: test-artifact
      - name: Cat file
        run: cat test.log # This job displays the content of the downloaded file
      
        

