name: Deploy to server
# This workflow deploys the application to a server using SSH.
on: 
  push:
    branches:
      - main
      - second
jobs:
  first_job:
    name : "First Job" # This job runs first
    runs-on: ubuntu-latest
    env:
      NAME : "World"
    steps:
      - name: Hola mundo # This job runs first
        run: echo "Hola ${{ env.NAME }}"
      - name: Working Directory
        run: ls -la # This job lists the files in the current directory
      - name: action
        uses: actions/checkout@v4 # This job checks out the code from the repository
      - name: Working Directory after Action
        run: ls -la # This job lists the files in the current directory
      - name: Working Directory after Action 2
        id: step_1
        run: echo "my_variable=Hola Mundo" >> $GITHUB_OUTPUT
      - name: Obtener mensaje
        run: echo "${{ steps.step_1.outputs.my_variable }}" # This job retrieves the variable set in the previous step
  second_job:
    if : ${{ github.ref == 'refs/heads/main' }} # This job runs only on the main branch
    # It depends on the first_job to complete before it runs
    needs: first_job # This job depends on the first_job
    runs-on: ubuntu-latest
    steps:
      - name: Hola mundo
        run: echo "Hola mundo segundo ${{ github.ref }} "
        

